# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Plucene-Plugin-Analyzer-SnowballAnalyzer
version:      1.1
version_from: lib/Plucene/Plugin/Analyzer/SnowballAnalyzer.pm
installdirs:  site
requires:
    Lingua::Stem::Snowball:        0
    Lingua::StopWords:             0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
